CREATE TABLE user_ships (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER,
  ship_name TEXT NOT NULL,
  thrusters TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP,
  CONSTRAINT fk_user
    FOREIGN KEY(user_id)
      REFERENCES logbook_users(id)
);    

--   user_id INTEGER
--       REFERENCES logbook_users(id) ON DELETE CASCADE NOT NULL,

  -- CONSTRAINT fk_user
  --   FOREIGN KEY(user_id)
  --     REFERENCES logbook_users(id)
