const thrusterList = [
  {name: 'T6 thrusters', cost: 3},
  {name: 'T8 thrusters', cost: 4},
  {name: 'T10 thrusters', cost: 5},
  {name: 'T12 thrusters', cost: 6},
  {name: 'T14 thrusters', cost: 7},
  {name: 'S6 thrusters', cost: 3},
  {name: 'S8 thrusters', cost: 4},
  {name: 'S10 thrusters', cost: 5},
  {name: 'S12 thrusters', cost: 6},
  {name: 'M4 thrusters', cost: 2},
  {name: 'M6 thrusters', cost: 3},
  {name: 'M8 thrusters', cost: 4},
  {name: 'M10 thrusters', cost: 5},
  {name: 'M12 thrusters', cost: 6},
  {name: 'L4 thrusters', cost: 4},
  {name: 'L6 thrusters', cost: 6},
  {name: 'L8 thrusters', cost: 8},
  {name: 'L10 thrusters', cost: 10},
  {name: 'H4 thrusters', cost: 4},
  {name: 'H6 thrusters', cost: 6},
  {name: 'H8 thrusters', cost: 8},
  {name: 'H10 thrusters', cost: 10},
  {name: 'G4 thrusters', cost: 8},
  {name: 'G6 thrusters', cost: 12},
  {name: 'G8 thrusters', cost: 16},
  {name: 'C4 thrusters', cost: 8},
  {name: 'C6 thrusters', cost: 12},
  {name: 'C8 thrusters', cost: 16},
]

module.exports = { thrusterList }
