const thrusterList = [
  {name: 'T6 thrusters', cost: 3},
  {name: 'T8 thrusters', cost: 4},
  {name: 'T10 thrusters', cost: 5},
  {name: 'T12 thrusters', cost: 6},
  {name: 'T14 thrusters', cost: 7},
  {name: 'S6 thrusters', cost: 3},
  {name: 'S8 thrusters', cost: 4},
  {name: 'S10 thrusters', cost: 5},
  {name: 'S12 thrusters', cost: 6},
  {name: 'M4 thrusters', cost: 2},
  {name: 'M6 thrusters', cost: 3},
  {name: 'M8 thrusters', cost: 4},
  {name: 'M10 thrusters', cost: 5},
  {name: 'M12 thrusters', cost: 6},
  {name: 'L4 thrusters', cost: 4},
  {name: 'L6 thrusters', cost: 6},
  {name: 'L8 thrusters', cost: 8},
  {name: 'L10 thrusters', cost: 10},
  {name: 'H4 thrusters', cost: 4},
  {name: 'H6 thrusters', cost: 6},
  {name: 'H8 thrusters', cost: 8},
  {name: 'H10 thrusters', cost: 10},
  {name: 'G4 thrusters', cost: 8},
  {name: 'G6 thrusters', cost: 12},
  {name: 'G8 thrusters', cost: 16},
  {name: 'C4 thrusters', cost: 8},
  {name: 'C6 thrusters', cost: 12},
  {name: 'C8 thrusters', cost: 16},
]

const coreList = [
  {name: 'Micron Light', cost: 4},
  {name: 'Micron Heavy', cost: 6},
  {name: 'Micron Ultra', cost: 8},
  {name: 'Arcus Light', cost: 7},
  {name: 'Pulse Brown', cost: 9},
  {name: 'Pulse Black', cost: 12},
  {name: 'Pulse White', cost: 14},
  {name: 'Pulse Gray', cost: 10},
  {name: 'Arcus Heavy', cost: 13},
  {name: 'Pulse Green', cost: 15},
  {name: 'Pulse Red', cost: 17},
  {name: 'Pulse Blue', cost: 20},
  {name: 'Arcus Ultra', cost: 15},
  {name: 'Arcus Maximum', cost: 20},
  {name: 'Pulse Orange', cost: 25},
  {name: 'Pulse Prismatic', cost: 30},
  {name: 'Nova Light', cost: 15},
  {name: 'Nova Heavy', cost: 20},
  {name: 'Nova Ultra', cost: 30},
  {name: 'Gateway Light', cost: 30},
  {name: 'Gateway Heavy', cost: 40},
  {name: 'Gateway Ultra', cost: 50},
]

module.exports = { thrusterList, coreList }
