const partsList = {
  findCost: (partType, partName) => {
    const part = partsList[partType].find(part => partName === part.name)
    const partCost = part.cost
    return partCost
  },
  thrustersList: [
    {name: 'T6 thrusters', cost: 3},
    {name: 'T8 thrusters', cost: 4},
    {name: 'T10 thrusters', cost: 5},
    {name: 'T12 thrusters', cost: 6},
    {name: 'T14 thrusters', cost: 7},
    {name: 'S6 thrusters', cost: 3},
    {name: 'S8 thrusters', cost: 4},
    {name: 'S10 thrusters', cost: 5},
    {name: 'S12 thrusters', cost: 6},
    {name: 'M4 thrusters', cost: 2},
    {name: 'M6 thrusters', cost: 3},
    {name: 'M8 thrusters', cost: 4},
    {name: 'M10 thrusters', cost: 5},
    {name: 'M12 thrusters', cost: 6},
    {name: 'L4 thrusters', cost: 4},
    {name: 'L6 thrusters', cost: 6},
    {name: 'L8 thrusters', cost: 8},
    {name: 'L10 thrusters', cost: 10},
    {name: 'H4 thrusters', cost: 4},
    {name: 'H6 thrusters', cost: 6},
    {name: 'H8 thrusters', cost: 8},
    {name: 'H10 thrusters', cost: 10},
    {name: 'G4 thrusters', cost: 8},
    {name: 'G6 thrusters', cost: 12},
    {name: 'G8 thrusters', cost: 16},
    {name: 'C4 thrusters', cost: 8},
    {name: 'C6 thrusters', cost: 12},
    {name: 'C8 thrusters', cost: 16},
  ],

  coreList: [
    {name: 'Micron Light', cost: 4},
    {name: 'Micron Heavy', cost: 6},
    {name: 'Micron Ultra', cost: 8},
    {name: 'Arcus Light', cost: 7},
    {name: 'Pulse Brown', cost: 9},
    {name: 'Pulse Black', cost: 12},
    {name: 'Pulse White', cost: 14},
    {name: 'Pulse Gray', cost: 10},
    {name: 'Arcus Heavy', cost: 13},
    {name: 'Pulse Green', cost: 15},
    {name: 'Pulse Red', cost: 17},
    {name: 'Pulse Blue', cost: 20},
    {name: 'Arcus Ultra', cost: 15},
    {name: 'Arcus Maximum', cost: 20},
    {name: 'Pulse Orange', cost: 25},
    {name: 'Pulse Prismatic', cost: 30},
    {name: 'Nova Light', cost: 15},
    {name: 'Nova Heavy', cost: 20},
    {name: 'Nova Ultra', cost: 30},
    {name: 'Gateway Light', cost: 30},
    {name: 'Gateway Heavy', cost: 40},
    {name: 'Gateway Ultra', cost: 50},
  ],

  armorList: [
    {name: 'Mk 1 armor', cost: 1},
    {name: 'Mk 2 armor', cost: 2},
    {name: 'Mk 3 armor', cost: 3},
    {name: 'Mk 4 armor', cost: 5},
    {name: 'Mk 5 armor', cost: 7},
    {name: 'Mk 6 armor', cost: 9},
    {name: 'Mk 7 armor', cost: 12},
    {name: 'Mk 8 armor', cost: 15},
    {name: 'Mk 9 armor', cost: 18},
    {name: 'Mk 10 armor', cost: 21},
    {name: 'Mk 11 armor', cost: 25},
    {name: 'Mk 12 armor', cost: 30},
    {name: 'Mk 13 armor', cost: 35},
    {name: 'Mk 14 armor', cost: 40},
    {name: 'Mk 15 armor', cost: 45},
  ],

  computerList: [
    {name: 'Basic Computer', cost: 0},
    {name: 'Mk 1 mononode', cost: 1},
    {name: 'Mk 1 duonode', cost: 2},
    {name: 'Mk 1 trinode', cost: 3},
    {name: 'Mk 1 tetranode', cost: 4},
    {name: 'Mk 2 mononode', cost: 4},
    {name: 'Mk 2 duonode', cost: 8},
    {name: 'Mk 2 trinode', cost: 12},
    {name: 'Mk 2 tetranode', cost: 16},
    {name: 'Mk 3 mononode', cost: 9},
    {name: 'Mk 3 duonode', cost: 18},
    {name: 'Mk 3 trinode', cost: 27},
    {name: 'Mk 3 tetranode', cost: 36},
    {name: 'Mk 4 mononode', cost: 16},
    {name: 'Mk 4 duonode', cost: 32},
    {name: 'Mk 4 trinode', cost: 48},
    {name: 'Mk 5 mononode', cost: 25},
    {name: 'Mk 5 duonode', cost: 50},
    {name: 'Mk 5 trinode', cost: 75},
    {name: 'Mk 6 mononode', cost: 36},
    {name: 'Mk 6 duonode', cost: 72},
    {name: 'Mk 7 mononode', cost: 49},
    {name: 'Mk 7 duonode', cost: 98},
    {name: 'Mk 8 mononode', cost: 64},
    {name: 'Mk 8 duonode', cost: 128},
    {name: 'Mk 9 mononode', cost: 81},
    {name: 'Mk 9 duonode', cost: 162},
    {name: 'Mk 10 mononode', cost: 100},
    {name: 'Mk 10 duonode', cost: 200},
  ],

  defensesList: [
    {name: 'Mk 1 defenses', cost: 2},
    {name: 'Mk 2 defenses', cost: 3},
    {name: 'Mk 3 defenses', cost: 4},
    {name: 'Mk 4 defenses', cost: 6},
    {name: 'Mk 5 defenses', cost: 8},
    {name: 'Mk 6 defenses', cost: 11},
    {name: 'Mk 7 defenses', cost: 14},
    {name: 'Mk 8 defenses', cost: 18},
    {name: 'Mk 9 defenses', cost: 22},
    {name: 'Mk 10 defenses', cost: 27},
    {name: 'Mk 11 defenses', cost: 33},
    {name: 'Mk 12 defenses', cost: 40},
    {name: 'Mk 13 defenses', cost: 50},
    {name: 'Mk 14 defenses', cost: 65},
    {name: 'Mk 15 defenses', cost: 90},
  ],

  sensorsList: [
    {name: 'Cut-rate', cost: 1},
    {name: 'Budget short-range', cost: 2},
    {name: 'Basic short-range', cost: 3},
    {name: 'Advanced short-range', cost: 4},
    {name: 'Budget medium-range', cost: 3},
    {name: 'Basic medium-range', cost: 5},
    {name: 'Advanced medium-range', cost: 8},
    {name: 'Budget long-range', cost: 6},
    {name: 'Basic long-range', cost: 10},
    {name: 'Advanced long-range', cost: 14},
  ],

  shieldsList: [
    {name: 'Mk 1 Basic Shields', cost: 2},
    {name: 'Mk 2 Basic Shields', cost: 3},
    {name: 'Mk 3 Basic Shields', cost: 4},
    {name: 'Mk 4 Basic Shields', cost: 5},
    {name: 'Mk 1 Light Shields', cost: 6},
    {name: 'Mk 2 Light Shields', cost: 8},
    {name: 'Mk 3 Light Shields', cost: 10},
    {name: 'Mk 4 Light Shields', cost: 12},
    {name: 'Mk 1 Medium Shields', cost: 13},
    {name: 'Mk 2 Medium Shields', cost: 15},
    {name: 'Mk 3 Medium Shields', cost: 17},
    {name: 'Mk 4 Medium Shields', cost: 18},
    {name: 'Mk 5 Medium Shields', cost: 20},
    {name: 'Mk 6 Medium Shields', cost: 22},
    {name: 'Mk 1 Heavy Shields', cost: 23},
    {name: 'Mk 2 Heavy Shields', cost: 25},
    {name: 'Mk 3 Heavy Shields', cost: 27},
    {name: 'Mk 4 Heavy Shields', cost: 28},
    {name: 'Mk 5 Heavy Shields', cost: 30},
    {name: 'Mk 6 Heavy Shields', cost: 32},
    {name: 'Mk 1 Superior Shields', cost: 35},
    {name: 'Mk 2 Superior Shields', cost: 40},
  ],

  enginesList: [
    {name: 'Signal Basic', cost: 2},
    {name: 'Signal Booster', cost: 5},
    {name: 'Signal Major', cost: 10},
    {name: 'Signal Superior', cost: 15},
    {name: 'Signal Ultra', cost: 20},
  ]
}

module.exports = { 
  partsList
}
